version: '3.7'

services:
  database_ig:
    image: postgres
    container_name: database_ig
    restart : always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=igrentalcars
    volumes:
      - pgdata:/data/postgres 
    
  app:
    build: .
    container_name: igrentalcars
    restart : always
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
      - node_modules:/user/app/node_modules
    links: 
      - database_ig
    depends_on: 
      - database_ig  
    
      

volumes:
  pgdata:
    driver: local
  node_modules: {}  
  

    
