version: '3.7'

services:
  database_ig:
    image: postgres
    container_name: database_ig
    restart : always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=igrentalcars
    volumes:
      - pgdata:/data/postgres  
    network_mode: host
  app:
    build: .
    container_name: igrentalcars
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    network_mode: host
volumes:
  pgdata:
    driver: local
